### ISSUE TITLE
Unable to specify Proxy for s3 input

### ISSUE THREAD

**Issue by todd-bowles-onthehouse** [logstash-plugins/logstash-input-s3#30]
My environment mandates that a proxy be used for all connections to the general internet.

Using the s3 input in 1.5.0.rc2 does not work as a result, because I cannot find a way to specify the proxy.

I tried setting the java environment proxy options with:

```
$env:LS_JAVA_OPTS="-Dhttp.proxyHost=$address -Dhttp.proxyPort=$port"
```

But it didnt seem to make much of a difference, I assume because its using the Ruby aws-sdk?

The error I get in the output is:

```
{:timestamp=>"2015-04-21T16:58:51.782000+1000", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::S3 bucket=>\"oth.console.liveagentservice.Test-tbowles-15110-12112.logs\", prefix=>\"ApiLoadBalancer\", region_endpoint=>\"ap-southeast-2\", region=>\"us-east-1\", temporary_directory=>\"C:/Windows/TEMP/logstash\">\n  Error: execution expired", :level=>:error}
```

The operative part is "Error: execution expired", which is typical for a request being made and timing out as a result of not going through the proxy.

I'm using Logstash 1.5.0.rc2 on a Windows machine. Does anyone know if the aws-sdk reads an environment variable for proxy settings or if there is some way that I can set it? I have a valid proxy in the HTTP_PROXY environment variable (of the form http://[ADDRESS]:[PORT]) and I can easily shift it around to wherever it is required.

Without the ability to use a proxy, I can't use the s3 input, which means I can't process the logs from ELB without significant additional effort (some sort of file sync from s3 to a local folder via Powershell, then processed by Logstash maybe?). I'd prefer to just use the S3 input.

**Comment by ph** [comment]
@todd-bowles-onthehouse you can try setting up the `http_proxy` environment variable
If i remember correctly this is the way to do it on windows:

```
set HTTP_PROXY=http://server:port
```

**Comment by todd-bowles-onthehouse** [comment]
Alas I have those variables set, but it doesn't seem to be respecting them.

I haven't returned to this in a while, but it might be a moot point anyway because:
* I might switch to a NAT box instead of a proxy (god I hate proxies).
* AWS has internal S3 endpoints available now, so to hell with proxies altogether.

**Comment by tuukkamustonen** [comment]
I'm running 1.5.3 and trying to use `proxy_uri` that is described in https://www.elastic.co/guide/en/logstash/current/plugins-inputs-s3.html

My config is like this:

      s3 {
        bucket => "mahbucket"
        type => "elb"
        prefix => "access-logs/"
        region => "eu-west-1"
        proxy_uri => "http://11.11.11.11:8080"
        delete => true
        interval => 60
      }

But I'm just getting:

    {:timestamp=>"2015-08-17T15:29:36.440000+0000", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::S3 bucket=>\"mahbucket\", type=>\"elb\", prefix=>\"access-logs/\", region=>\"eu-west-1\", proxy_uri=>\"http://11.11.11.11:8080\", delete=>true, interval=>60, debug=>false, codec=><LogStash::Codecs::Plain charset=>\"UTF-8\">, use_ssl=>true, temporary_directory=>\"/var/lib/logstash/logstash\">\n  Error: execution expired", :level=>:error}

That's the same output as without `proxy_uri` option - just doesn't seem that the option does anything.

I can successfully fetch files from s3 using aws cli and something like:

    https_proxy=http://11.11.11.11:8080 aws s3 cp s3://mahbucket/somefile.tar.gz .

So proxy config should be ok, still, nothing changes when I add `proxy_uri` and restart.

**Comment by torrancew** [comment]
This came up in IRC today, and I helped user @kylerankin look into it.

It turns out that a small bug in the s3 input is preventing the proxy setting from ever taking affect.
As @ph mentions [here](https://github.com/logstash-plugins/logstash-input-s3/issues/14#issuecomment-77871626), the way that certain methods are invoked prevents the environment variable from having any effect. Unfortunately, the [default value for the `credentials` setting in this plugin](https://github.com/logstash-plugins/logstash-input-s3/issues/14#issuecomment-77871626) is an empty array, which causes [this condition](https://github.com/logstash-plugins/logstash-input-s3/blob/master/lib/logstash/inputs/s3.rb#L353-L361) to always pass. As a result, the AWS::S3 constructor is never actually invoked with the full aws_options_hash, and the proxy directive is never honored.

A unit test to check whether we actually pass that parameter through to the upstream constructor should at least help highlight this bug, and changing the "if @credentials" to "if @credentials and ! @credentials.empty" should resolve the issue.

**Comment by ph** [comment]
@torrancew thanks for looking into this, can you create a PR for it?

**Comment by torrancew** [comment]
@ph I'm working on that now, actually. It has some intersections with #46 and #25, but is small enough that I think it may make sense to merge it in regardless.

**Comment by ph** [comment]
Thanks @torrancew ! Yeah it make sense to merge.

**Comment by vjagannath786** [comment]
Getting same error, logstash is not taking proxy_uri from conf file and getting seahorse::client::networking error, but when tried with awscli it is working. 
I have tried with 6.8.0 and 7.8.1 version as well.
